#!/usr/bin/env python

from Worker import Worker


"""
@class

Tractor class. Inherits from the Worker class. The behaviour of this entity will consist
of patrolling up and down empty orchard rows, and will leave a orchard if a robot enters its current
row.

This entity subsribes to topics generated by the Picker and Carrier class, then stores coordinates of
Picker and Carrier entities into a dictionary. This information is used to determine if an orchard row is
empty or not, and also allows the worker entity to detect if a robot enters the row it is currently in.
"""

class Tractor(Worker):
    def __init__(self, r_name, r_id, x_off, y_off, theta_offset):
        Worker.__init__(self, r_name, r_id, x_off, y_off, theta_offset)